In [2]:
import numpy as np

In [11]:
x = np.random.rand(2, 2, 2)
x

array([[[0.09655411, 0.05796718],
        [0.28573144, 0.05147156]],

       [[0.77855893, 0.01118148],
        [0.31498066, 0.32990603]]])

In [15]:
y = x.sum(axis=2)[0, 1]     
y

0.3372030039982804

In [13]:
z = x[0, 1, :].sum()
z

0.3372030039982804

In [16]:
test = x[0, 1, ].sum()
test

0.3372030039982804

In [52]:
x = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])
x.astype(int)
x.shape

(3, 3, 3)

In [53]:
s, t, u = np.array_split(x, 3)
print(u, u.shape)

[[[18 19 20]
  [21 22 23]
  [24 25 26]]] (1, 3, 3)


In [56]:
# create 2D array from 2 1D arrays
concat_t_u = np.vstack((t, u))
concat_t_u

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
math_arr = 2/concat_t_u
math_arr

array([[[0.22222222, 0.2       , 0.18181818],
        [0.16666667, 0.15384615, 0.14285714],
        [0.13333333, 0.125     , 0.11764706]],

       [[0.11111111, 0.10526316, 0.1       ],
        [0.0952381 , 0.09090909, 0.08695652],
        [0.08333333, 0.08      , 0.07692308]]])

In [60]:
regroup_arr = np.vstack((s, math_arr))
regroup_arr

array([[[0.        , 1.        , 2.        ],
        [3.        , 4.        , 5.        ],
        [6.        , 7.        , 8.        ]],

       [[0.22222222, 0.2       , 0.18181818],
        [0.16666667, 0.15384615, 0.14285714],
        [0.13333333, 0.125     , 0.11764706]],

       [[0.11111111, 0.10526316, 0.1       ],
        [0.0952381 , 0.09090909, 0.08695652],
        [0.08333333, 0.08      , 0.07692308]]])